
-- Create a table to store world configurations
CREATE TABLE public.worlds (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  component_key TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Add a comment to describe the table's purpose
COMMENT ON TABLE public.worlds IS 'Stores configuration and metadata for each explorable world.';

-- Enable Row Level Security to control access
ALTER TABLE public.worlds ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone to read the worlds data
CREATE POLICY "Allow public read-only access to worlds"
ON public.worlds
FOR SELECT
USING (true);

-- Insert the initial three worlds into the table
INSERT INTO public.worlds (name, description, component_key) VALUES
('Genesis Torus', 'A primordial structure adrift in the cosmos.', 'World1'),
('Wobble Field', 'A chaotic space of unstable matter.', 'World2'),
('Distortion Sphere', 'A reality-bending celestial body.', 'World3');

