
-- Create a table for event logging
CREATE TABLE public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_type TEXT NOT NULL,
  event_source TEXT,
  metadata JSONB
);

-- RLS is disabled for this table to allow anonymous logging for analytics.
-- Anyone can write to it. If read access needs to be restricted,
-- policies can be added later.
