// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpqadqhqphmtdkepvnet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwcWFkcWhxcGhtdGRrZXB2bmV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDg0OTMsImV4cCI6MjA2NTUyNDQ5M30.cxyPs3buUZsOMyhMiNr25RexN8MZL9QWBbUGX4--084";


export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);