name: Delete branch on PR close

on:
    pull_request:
        types: [closed]

jobs:
    delete_head_branch:
        runs-on: ubuntu-latest
        steps:
            - name: Delete branch
              uses: dawidd6/action-delete-branch@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  # Only delete if not merged
                  branches: ${{ github.event.pull_request.head.ref }}
              if: github.event.pull_request.merged == false
