name: Super-Linter

on: [pull_request]

jobs:
    super-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Run Super-Linter
              uses: github/super-linter/slim@v5
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VALIDATE_JAVASCRIPT_ES: false  # Disable ESLint for JS
                  VALIDATE_TYPESCRIPT_ES: false  # Disable ESLint for TS
                  VALIDATE_JSX: false             # Disable ESLint for JSX
                  VALIDATE_TSX: false             # Disable ESLint for TSX
                  VALIDATE_CSS: true
                  VALIDATE_MARKDOWN: true
                  VALIDATE_YAML: true
                  VALIDATE_JSON: true
